apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  # Database configuration
  DB_HOST: "postgres-service"
  DB_NAME: "DBLAB"
  POSTGRES_DB: "DBLAB"
  
  # Backend configuration
  BACKEND_PORT: "8000"
  
  # Frontend configuration (nginx upstream)
  BACKEND_URL: "http://backend-service:8000"
